[package]
name = "hyprland-input-socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo = "0.0.4"
gdk4 = "0.7.3"
gtk4 = "0.7.3"
gtk4-layer-shell = "0.2.0"
